### ISSUE TITLE
Suggest moving away from ktlint-gradle

### ISSUE THREAD

**Issue by stackunderflows** [AdamMc331/AndroidAppTemplate#17]
JLLeitschuh doesn't appear very well maintained these days. There are a ton of github issues and the maintainers admit they don't have time to keep up. I suggest finding a replacement for this plugin. 

https://github.com/JLLeitschuh/ktlint-gradle/issues/569

**Comment by AdamMc331** [comment]
Thanks for the suggestion! Looks like no new maintainers have stepped up just yet. Have you seen any alternative gradle plugins?

**Comment by mrmans0n** [comment]
kotlinter seems to be the only actively maintained solution as of late, and migrating from ktlint-gradle to it is a breeze

**Comment by AdamMc331** [comment]
Will try [kotlinter](https://github.com/jeremymailen/kotlinter-gradle)!

**Comment by AdamMc331** [comment]
Done. Thanks for the suggestions @mrmans0n and @stackunderflows!
