### ISSUE TITLE
Hilt?

### ISSUE THREAD

**Issue by stackunderflows** [AdamMc331/AndroidAppTemplate#30]
Have you thought about adding Hilt to this template? I think it would be a great addition.

**Comment by AdamMc331** [comment]
Hmmm so I did think about this, but I left it out a little bit on purpose to leave decisions like that to the users. While the template is opinionated about some things (like which static analysis frameworks are used), I didn't want to make decisions about navigation, architecture, screen setup, or anything like that. 

I'll leave this issue open for a little bit in case other folks come in and disagree, we can always consider adding a hilt branch that people can use or delete later on, but I'm leaning toward not making this decision.

**Comment by AdamMc331** [comment]
After further thought, I mostly feel that we shouldn't write code that enforces how the user uses the template. 

However, I am open to at least providing the gradle dependencies, which would resolve a portion of the issue. We could add the hilt plugin and its relevant dependency implementations, and if the end user of the template doesn't want to use Hilt, they could just delete those lines. We could even make it part of the setup.gradle file. 

Does this seem like a good compromise?

**Comment by stackunderflows** [comment]
> After further thought, I mostly feel that we shouldn't write code that enforces how the user uses the template.
> 
> However, I am open to at least providing the gradle dependencies, which would resolve a portion of the issue. We could add the hilt plugin and its relevant dependency implementations, and if the end user of the template doesn't want to use Hilt, they could just delete those lines. We could even make it part of the setup.gradle file.
> 
> Does this seem like a good compromise?

Yes, that sounds like a good compromise.
