### ISSUE TITLE
Consider adding gradle-build-action to CI tasks

### ISSUE THREAD

**Issue by StylianosGakis** [AdamMc331/AndroidAppTemplate#49]
The gradle build action https://github.com/gradle/gradle-build-action has [a section](https://github.com/gradle/gradle-build-action#why-use-the-gradle-build-action) about why to use it.

NowInAndroid is using it for example here https://github.com/android/nowinandroid/blob/d9057010282c48d257cd742701350108c27daa5d/.github/workflows/Build.yaml#L33-L34 for reference.

Maybe something like this should be part of this template? What do you think?

**Comment by AdamMc331** [comment]
Sure! I think this is something I can try to add in. :)

**Comment by AdamMc331** [comment]
Added this, gonna make a new branch shortly to see how much faster they are with caching happening on development branch.
