### ISSUE TITLE
Apply the `gradle-versions` plugin to the root project.

### ISSUE THREAD

**Issue by itsusmon** [AdamMc331/AndroidAppTemplate#50]
Hey Adam! 

I found a little issue here.

By applying the versions plugin to each submodule, you're creating individual report files for each module. The issue here, you are only using the report file inside the app module in your `Danger` reports. The rest of them are just useless.

The solution I can offer is: Apply the versions plugin to the root project. The plugin automatically looks through all of the submodule's dependencies and then combines them into a single report file.

After that, you need to change the report file path in your `Dangerfile`, the output report file path will be `build/dependencyUpdates/report.txt`

**Comment by AdamMc331** [comment]
Nice catch! Will look into it this week.

**Comment by AdamMc331** [comment]
Added this, gonna make a new branch shortly to see how much faster they are with caching happening on development branch.
