### ISSUE TITLE
Windows support on githooks.

### ISSUE THREAD

**Issue by dogancankilic** [AdamMc331/AndroidAppTemplate#51]
I wonder is it possible to support also Windows on git hooks?

**Comment by AdamMc331** [comment]
Hmm, I thought I tested this back when I shipped the template but maybe it's still broken. I'll investigate this week, thanks for flagging!

**Comment by AdamMc331** [comment]
Windows solution: https://emmanuelkehinde.io/setting-up-git-pre-commit-pre-push-hook-for-ktlint-check/

Will be revisiting end of April when I return from a trip.

**Comment by AdamMc331** [comment]
PR is up, didn't test on my own windows machine but added GH actions to verify install works well: https://github.com/AdamMc331/AndroidAppTemplate/pull/165
